### ISSUE TITLE
"Could not resolve dependencies for project" error

### ISSUE THREAD

**Issue by joewiz** [adamretter/exist-expath-file-module#1]
When I clone the repo to my local system (Mac OS X 10.11.3) and run `mvn package` I get an error:

```
$ mvn -e package

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building eXist EXPath File Module 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.exist-db:existdb-core:jar:2.3-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.exquery.expath:expath-file-module:jar:1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.414 s
[INFO] Finished at: 2016-02-01T20:14:26+08:00
[INFO] Final Memory: 7M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project file-module: Could not resolve dependencies for project org.exist.expath.module:file-module:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.exist-db:existdb-core:jar:2.3-SNAPSHOT, org.exquery.expath:expath-file-module:jar:1.0-SNAPSHOT: Failure to find org.exist-db:existdb-core:jar:2.3-SNAPSHOT in https://raw.github.com/eXist-db/mvn-repo/master/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project file-module: Could not resolve dependencies for project org.exist.expath.module:file-module:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.exist-db:existdb-core:jar:2.3-SNAPSHOT, org.exquery.expath:expath-file-module:jar:1.0-SNAPSHOT: Failure to find org.exist-db:existdb-core:jar:2.3-SNAPSHOT in https://raw.github.com/eXist-db/mvn-repo/master/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:199)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.exist.expath.module:file-module:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: org.exist-db:existdb-core:jar:2.3-SNAPSHOT, org.exquery.expath:expath-file-module:jar:1.0-SNAPSHOT: Failure to find org.exist-db:existdb-core:jar:2.3-SNAPSHOT in https://raw.github.com/eXist-db/mvn-repo/master/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 23 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.exist-db:existdb-core:jar:2.3-SNAPSHOT, org.exquery.expath:expath-file-module:jar:1.0-SNAPSHOT: Failure to find org.exist-db:existdb-core:jar:2.3-SNAPSHOT in https://raw.github.com/eXist-db/mvn-repo/master/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.exist-db:existdb-core:jar:2.3-SNAPSHOT, org.exquery.expath:expath-file-module:jar:1.0-SNAPSHOT: Failure to find org.exist-db:existdb-core:jar:2.3-SNAPSHOT in https://raw.github.com/eXist-db/mvn-repo/master/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find org.exist-db:existdb-core:jar:2.3-SNAPSHOT in https://raw.github.com/eXist-db/mvn-repo/master/ was cached in the local repository, resolution will not be reattempted until the update interval of exist has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 27 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by adamretter** [comment]
Thanks for reporting @joewiz. The dependency was out of date, I have fixed that here: 8ea367c591014752b6827ba1dc3da4221cfba019.

You will also need to build and install the expath-file-module from the EXQuery project first. I have updated README.md with the instructions.
